@host = http://localhost:8888
@token = admin_token

// authenticate
POST {{host}}/authenticate

{
    "email": "admin@example.com",
    "password": "adminPassword"
}

### // create students

POST {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Some Student 1",
    "email": "student1@example.com",
    "password": "student1Password",
    "role": "student"
}

###

POST {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Some Student 2",
    "email": "student2@example.com",
    "password": "student2Password",
    "role": "student"
}

###

POST {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Some Student 3",
    "email": "student3@example.com",
    "password": "student3Password",
    "role": "student"
}

### // create teachers

POST {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Some Teacher 1",
    "email": "teacher1@example.com",
    "password": "teacher1Password",
    "role": "teacher"
}

###

POST {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Some Teacher 2",
    "email": "teacher2@example.com",
    "password": "teacher2Password",
    "role": "teacher"
}

### // create parents

POST {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Some Parent 1",
    "email": "parent1@example.com",
    "password": "parent1Password",
    "role": "parent"
}

###

POST {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Some Parent 2",
    "email": "parent2@example.com",
    "password": "parent2Password",
    "role": "parent"
}

### // get all users

GET {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

### // update user

PATCH {{host}}/users/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Student 1"
}

### // get user by id

GET {{host}}/users/2
Content-Type: application/json
Authorization: Bearer {{token}}

### // create new classes

POST {{host}}/classes
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "12.a",
    "teacher_id": 5
}

###

POST {{host}}/classes
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "12.b",
    "teacher_id": 6
}

### // update class
PATCH {{host}}/classes/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "11.a"
}

### // set students' classes
PUT {{host}}/students/2/class
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "class_id": 1
}

###

PUT {{host}}/students/3/class
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "class_id": 1
}

###

PUT {{host}}/students/4/class
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "class_id": 2
}

### // create subjects

POST {{host}}/subjects
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Mathematics"
}

###

POST {{host}}/subjects
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Estonian"
}

###

POST {{host}}/subjects
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Russian (B1)"
}

###

POST {{host}}/subjects
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "English (B2)"
}

### // update subject

PATCH {{host}}/subjects/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Advanced Mathematics"
}

### // create grades

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identifier": "5+",
    "value": 100
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identifier": "5",
    "value": 100
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identifier": "5-",
    "value": 100
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identifier": "4+",
    "value": 90
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identifier": "4",
    "value": 90
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identifier": "4-",
    "value": 90
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identifier": "3+",
    "value": 75
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identifier": "3",
    "value": 75
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identifier": "3-",
    "value": 75
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identifier": "2",
    "value": 50
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identifier": "1",
    "value": 25
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identifier": "A",
    "value": 100
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "identifier": "MA",
    "value": 50
}

### // update grade

PATCH {{host}}/grades/11
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "value": 20
}

### // create groups

POST {{host}}/groups
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "All Students"
}

###

POST {{host}}/groups
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "All Teachers"
}

###

POST {{host}}/groups
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Everybody"
}

###

POST {{host}}/groups
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Bad"
}

### // remove group

DELETE {{host}}/groups/4
Authorization: Bearer {{token}}

### // update group

PATCH {{host}}/groups/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Everyone"
}

### // add users to groups

POST {{host}}/groups/1/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_ids": [2,3,4,5]
}

###

POST {{host}}/groups/2/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_ids": [1,5,6]
}

###

POST {{host}}/groups/3/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_ids": [1,2,3,4,5,6,7,8]
}

### // remove user from group

DELETE {{host}}/groups/1/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_ids": [5]
}

### // add parents to students

PUT {{host}}/students/2/parents
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "parent_id": 7
}

###

PUT {{host}}/students/3/parents
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "parent_id": 7
}

###

PUT {{host}}/students/4/parents
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "parent_id": 8
}

###

PUT {{host}}/students/4/parents
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "parent_id": 7
}

### // remove parent from student

DELETE {{host}}/students/4/parents
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "parent_id": 7
}

###