@host = http://localhost:8888
@token = O3XXBJOZHRVJX2CTNDPQCWTJWM

// authenticate
POST {{host}}/authenticate
Content-Type: application/json

{
    "email": "teacher2@example.com",
    "password": "teacher2Password"
}

### // create journals

POST {{host}}/journals
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "12.a Estonian",
    "subject_id": 2
}

###

POST {{host}}/journals
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "11.a Estonian",
    "subject_id": 2
}

### // add students to journals

POST {{host}}/journals/3/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "student_id": 2
}

###

POST {{host}}/journals/3/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "student_id": 3
}

###

POST {{host}}/journals/3/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "student_id": 4
}

###

POST {{host}}/journals/4/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "student_id": 4
}

### // remove user from journal

DELETE {{host}}/journals/3/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "student_id": 4
}

### // get students for journal
GET {{host}}/journals/3/students
Authorization: Bearer {{token}}

###

GET {{host}}/journals/4/students
Authorization: Bearer {{token}}

### // get journals for teacher
GET {{host}}/teachers/6/journals
Authorization: Bearer {{token}}

### // add marks

POST {{host}}/marks
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 3,
    "journal_id": 3,
    "grade_id": 5,
    "type": "subject_grade"
}

###

POST {{host}}/marks
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 2,
    "journal_id": 3,
    "grade_id": 1,
    "type": "subject_grade"
}

###

POST {{host}}/marks
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 4,
    "course": 5,
    "journal_id": 4,
    "grade_id": 4,
    "type": "course_grade"
}

### // get user by id

GET {{host}}/users/6
Authorization: Bearer {{token}}

###

GET {{host}}/users/2
Authorization: Bearer {{token}}

### // get student's class

GET {{host}}/students/2/class
Authorization: Bearer {{token}}

### // get students in class

GET {{host}}/classes/2/students
Authorization: Bearer {{token}}

### // get journal by id

GET {{host}}/journals/3
Authorization: Bearer {{token}}

### // get lessons for journals
GET {{host}}/journals/4/lessons
Authorization: Bearer {{token}}

### // get all grades
GET {{host}}/grades
Authorization: Bearer {{token}}

### // get group by id
GET {{host}}/groups/2
Authorization: Bearer {{token}}

### // get groups by user id
GET {{host}}/users/6/groups
Authorization: Bearer {{token}}

### // create message
POST {{host}}/threads/1/messages
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "body": "I also wanted to add that..."
}

### // delete message
DELETE {{host}}/messages/1
Authorization: Bearer {{token}}

### // get threads for user
GET {{host}}/users/6/threads
Authorization: Bearer {{token}}

### // get thread by id
GET {{host}}/threads/1
Authorization: Bearer {{token}}

### // get all sessions for user
GET {{host}}/users/6/sessions
Authorization: Bearer {{token}}