@host = http://localhost:8888
@adminToken = token1
@parentToken = token2
@studentToken = token3

######################################################### USERS

// create student
POST {{host}}/users
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "name": "Some Student",
    "email": "some.student@example.com",
    "password": "password",
    "role": "student"
}

###

// create admin/teacher
POST {{host}}/users
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "name": "Some Admin",
    "email": "some.admin@example.com",
    "password": "password",
    "role": "admin"
}

###

// create parent
POST {{host}}/users
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "name": "Some Parent",
    "email": "some.parent@example.com",
    "password": "password",
    "role": "parent"
}

###

// get user by id
GET {{host}}/users/1
Authorization: Bearer {{adminToken}}

###

// update user
PATCH {{host}}/users/2
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "name": "Another Admin",
    "password": "NewPassword"
}

###

// list all users
GET {{host}}/users
Authorization: Bearer {{adminToken}}

######################################################### CLASSES

// create class
POST {{host}}/classes
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "name": "11a",
    "teacher_id": 2
}

###

// get class by id
GET {{host}}/classes/1
Authorization: Bearer {{adminToken}}

###

// update class
PATCH {{host}}/classes/1
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "12a",
    "teacher_id": 2
}

###

// get all classes
GET {{host}}/classes
Authorization: Bearer {{adminToken}}

###

// get student's class
GET {{host}}/students/1/class
Authorization: Bearer {{adminToken}}

###

// set student's class
PUT {{host}}/students/1/class
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "class_id": 1
}

###

// get all students in class
GET {{host}}/classes/1/students
Authorization: Bearer {{parentToken}}

######################################################### SUBJECTS

// create subject
POST {{host}}/subjects
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "name": "Mathematics"
}

###

// get subject by id
GET {{host}}/subjects/1
Authorization: Bearer {{adminToken}}

###

// update subject
PATCH {{host}}/subjects/1
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "name": "Advanced Mathematics"
}

###

// list all subjects
GET {{host}}/subjects
Authorization: Bearer {{adminToken}}

######################################################### JOURNALS

// create journal

POST {{host}}/journals
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "name": "12a Advanced Mathematics",
    "teacher_id": 2,
    "subject_id": 1
}

###

// get journal by id
GET {{host}}/journals/1
Authorization: Bearer {{adminToken}}

###

// update journal
PATCH {{host}}/journals/1
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "12a Mathematics Advanced",
    "teacher_id": 2
}

###

// get all journals
GET {{host}}/journals
Authorization: Bearer {{adminToken}}

###

// get journals for teacher
GET {{host}}/teachers/2/journals
Authorization: Bearer {{adminToken}}

###

// add student to journal
POST {{host}}/students/1/journals
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "journal_id": 1
}

###

// remove student from journal
DELETE {{host}}/students/1/journals
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "journal_id": 1
}

###

// add student to journal (again)
POST {{host}}/students/1/journals
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "journal_id": 1
}

###

// get students for journal
GET {{host}}/journals/1/students
Authorization: Bearer {{adminToken}}

###

// get journals for student
GET {{host}}/students/1/journals
Authorization: Bearer {{adminToken}}

######################################################### LESSONS

// create lesson
POST {{host}}/lessons
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "journal_id": 1,
    "description": "Algebra; p. 90-95 ex 1-6",
    "date": "2022-06-30",
    "course": 1
}

###

// get lesson by id
GET {{host}}/lessons/1
Authorization: Bearer {{adminToken}}

###

// update lesson
PATCH {{host}}/lessons/1
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "description": "Algebra I Revision: p. 80-85",
    "date": "2022-06-29"
}

###

// get lessons for journal
GET {{host}}/journals/1/lessons
Authorization: Bearer {{adminToken}}

######################################################### ASSIGNMENTS

// create assignment
POST {{host}}/assignments
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "journal_id": 1,
    "description": "Test: Algebra I",
    "deadline": "2022-07-01",
    "type": "test"
}

###

// update assignment
PATCH {{host}}/assignments/1
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "description": "Test: Algebra I Advanced",
    "deadline": "2022-07-04",
    "type": "test"
}

###

// get assignment by id
GET {{host}}/assignments/1
Authorization: Bearer {{adminToken}}

###

// delete assignment
DELETE {{host}}/assignments/1
Authorization: Bearer {{adminToken}}

###

// create assignment (again)
POST {{host}}/assignments
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "journal_id": 1,
    "description": "Algebra I revision: p. 90-95 ex. 1-6",
    "deadline": "2022-07-04",
    "type": "homework"
}

###

// get all assignments for journal
GET {{host}}/journals/1/assignments
Authorization: Bearer {{adminToken}}

###

// get all assignments for student
GET {{host}}/students/1/assignments
Authorization: Bearer {{adminToken}}

###

// set assignment done for student
PUT {{host}}/students/1/assignments/2/done
Authorization: Bearer {{adminToken}}

###

// remove assignment done for student
DELETE {{host}}/students/1/assignments/2/done
Authorization: Bearer {{adminToken}}

######################################################### GRADES

// create some grades

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "identifier": "5",
    "value": 100
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "identifier": "4",
    "value": 90
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "identifier": "3",
    "value": 75
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "identifier": "2",
    "value": 50
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "identifier": "1",
    "value": 20
}

###

POST {{host}}/grades
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "identifier": "F",
    "value": 10
}

###

// get all grades
GET {{host}}/grades
Authorization: Bearer {{adminToken}}

###

// update grade
PATCH {{host}}/grades/5
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "identifier": "1",
    "value": 15
}

###

// get grade by id
GET {{host}}/grades/5
Authorization: Bearer {{adminToken}}

######################################################### MARKS

// ADDING MARKS

// adding lesson grades
POST {{host}}/marks
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "user_id": 1,
    "lesson_id": 1,
    "grade_id": 1,
    "comment": "100%",
    "type": "lesson_grade"
}

###

POST {{host}}/marks
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "user_id": 1,
    "lesson_id": 1,
    "grade_id": 3,
    "comment": "80%",
    "type": "lesson_grade"
}

###

// adding good notice
POST {{host}}/marks
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "user_id": 1,
    "lesson_id": 1,
    "comment": "<insert good comment here>",
    "type": "notice_good"
}

###

// adding course grade
POST {{host}}/marks
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "user_id": 1,
    "course": 1,
    "journal_id": 1,
    "grade_id": 2,
    "type": "course_grade"
}

###

// get current marks for student
GET {{host}}/students/1/marks
Authorization: Bearer {{adminToken}}

###

// adding subject grade
POST {{host}}/marks
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "user_id": 1,
    "journal_id": 1,
    "grade_id": 2,
    "type": "subject_grade"
}

###

// deleting mark
DELETE {{host}}/marks/2
Authorization: Bearer {{adminToken}}

###

// updating lesson grade
PATCH {{host}}/marks/1
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "grade_id": 2,
    "comment": "90%"
}

###

// get current marks for journal
GET {{host}}/journals/1/marks
Authorization: Bearer {{adminToken}}

###

// updating notice
PATCH {{host}}/marks/3
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "comment": "very good!"
}

###

// get current marks for student's journal
GET {{host}}/students/1/journals/1/marks
Authorization: Bearer {{adminToken}}

###

// get previous marks for mark
GET {{host}}/marks/1/previous
Authorization: Bearer {{adminToken}}

###

// add absence to student
POST {{host}}/marks
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "user_id": 1,
    "lesson_id": 1,
    "type": "absent"
}

###

// get absences for student
GET {{host}}/students/1/absences
Authorization: Bearer {{adminToken}}

###

// add excuse for student's absence
POST {{host}}/students/1/excuses
Authorization: Bearer {{adminToken}}

{"absence_id": 6, "excuse": "xx"}

###

// delete excuse for student's absence
DELETE {{host}}/students/1/excuses/7
Authorization: Bearer {{adminToken}}

######################################################### GROUPS

// create group

POST {{host}}/groups
Authorization: Bearer {{adminToken}}

{
    "name": "Students"
}

###

// update group
Authorization: Bearer {{adminToken}}

PATCH {{host}}/groups/2

{"name": "All students"}

###

// delete group

DELETE {{host}}/groups/2
Authorization: Bearer {{adminToken}}

###

// create group (again)

POST {{host}}/groups
Authorization: Bearer {{adminToken}}

{
    "name": "Everyone"
}

###

// get group

GET {{host}}/groups/3
Authorization: Bearer {{adminToken}}

###

// add users to group
POST {{host}}/groups/3/users
Authorization: Bearer {{adminToken}}

{"user_ids": [1, 2]}

###

// remove users from group
DELETE {{host}}/groups/3/users
Authorization: Bearer {{adminToken}}

{"user_ids": [1]}

###

// get all groups
GET {{host}}/groups
Authorization: Bearer {{adminToken}}

###

// get groups for user
GET {{host}}/users/1/groups
Authorization: Bearer {{adminToken}}

###

// get users for groups
GET {{host}}/groups/3/users
Authorization: Bearer {{adminToken}}

######################################################### THREADS

// create thread
POST {{host}}/threads
Authorization: Bearer {{adminToken}}

{
    "title": "my thread 2",
    "body": "cool",
    "user_ids": [1,5]
}
 
###

// delete thread
DELETE {{host}}/threads/8
Authorization: Bearer {{adminToken}}

###

// lock thread
PUT {{host}}/threads/9/lock
Authorization: Bearer {{adminToken}}

###

// unlock thread
PUT {{host}}/threads/9/unlock
Authorization: Bearer {{adminToken}}

###

// add users to thread
PUT {{host}}/threads/9/users
Authorization: Bearer {{adminToken}}

{
    "user_ids": [1,2,5]
}

###

// remove users from thread
DELETE {{host}}/threads/9/users
Authorization: Bearer {{adminToken}}

{
    "user_ids": [1,5]
}

###

// update thread
PUT {{host}}/threads/9
Authorization: Bearer {{adminToken}}

{"body": "eyeyeyey", "title": "x"}

###

// get threads for user
GET {{host}}/users/2/threads
Authorization: Bearer {{adminToken}}

###

// create message
POST {{host}}/threads/9/messages
Authorization: Bearer {{adminToken}}

{
    "body": "msg"
}

###

// update message
PUT {{host}}/messages/5
Authorization: Bearer {{adminToken}}

{
    "body": "msgx"
}

###

// delete message
DELETE {{host}}/messages/4
Authorization: Bearer {{adminToken}}

###

// get thread
GET {{host}}/threads/12
Authorization: Bearer {{adminToken}}

######################################################### AUTHENTICATION

// authenticate user
POST {{host}}/authenticate

{
    "email": "some.parent@example.com",
    "password": "password"
}

###

// get sessions for user

GET {{host}}/users/2/sessions
Authorization: Bearer {{adminToken}}

###

// delete specific session
DELETE {{host}}/sessions/6
Authorization: Bearer {{adminToken}}

###

// delete all sessions for user
DELETE {{host}}/users/2/sessions
Authorization: Bearer {{adminToken}}

######################################################### PARENT

// set parent for student
PUT {{host}}/students/1/parents
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "parent_id": 7
}

###

// get parents for student
GET {{host}}/students/1/parents
Content-Type: application/json
Authorization: Bearer {{studentToken}}

###

// remove parent from student
DELETE {{host}}/students/1/parents
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "parent_id": 7
}